# Generated by Django 5.0.2 on 2024-03-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep_image',
            field=models.ImageField(upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='image',
            field=models.ImageField(upload_to='testpackage'),
        ),
    ]
