# Generated by Django 5.0.2 on 2024-03-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0002_rename_description_blogs_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='count',
        ),
    ]
