# Generated by Django 5.0.2 on 2024-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0005_branches_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.IntegerField(max_length=13),
        ),
    ]
