# Generated by Django 5.0.2 on 2024-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0007_alter_branches_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_tests',
            name='testes',
            field=models.TextField(default=0, help_text='Enter test names separated by commas'),
            preserve_default=False,
        ),
    ]
