# Generated by Django 5.0.2 on 2024-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0009_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_decrption',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='dep_detail_banner',
            field=models.ImageField(default=0, upload_to='departmentbanner/'),
            preserve_default=False,
        ),
    ]
