# Generated by Django 5.0.2 on 2024-03-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0011_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
