# Generated by Django 5.0.2 on 2024-03-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_number', models.IntegerField(unique=True)),
                ('blog_image', models.ImageField(upload_to='Blogs/')),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_place', models.CharField(max_length=200)),
                ('branch_image', models.ImageField(upload_to='branch/')),
                ('branch_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=150, unique=True)),
                ('dep_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='Gallery/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News_and_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurTestinomials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('place', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='test_package_images/')),
                ('tests', models.TextField(help_text='Enter test names separated by commas')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('blog_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frondpage.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150, unique=True)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frondpage.tests')),
            ],
        ),
    ]
