# Generated by Django 5.0.2 on 2024-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0004_branches_address_branches_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
