# Generated by Django 5.0.2 on 2024-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frondpage', '0010_departments_dep_decrption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsandConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
